on:
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: schema check
        env:
          HIVE_TOKEN: ${{ secrets.HIVE_ACCESS_TOKEN }}
        run: |
          curl -sSL https://graphql-hive.com/install.sh | sh
          hive schema:check ./subgraphs/accounts/src/main.ts  \
            --service accounts \
            --registry.accessToken ${{ env.HIVE_TOKEN }} \
            --github
